### PR TITLE
applied search-replace fix to make compatible with pd-0.52-1

### PR DESCRIPTION
**Pull request by shakfu**
Applied:

```
rpl -R -x ".c" " error(" " pd_error(0, " .
```

Key change is as follows

```
error(<msg>) -> pd_error(0, <msg>)
```

### CODE REVIEW

**Comment by porres** [comment]
hi, what is the problem of keeping as it is? and where is the new 'error' function in the pd code?

**Comment by ericlyon** [comment]
My understanding is that error() was replaced with pd_error() from Pd-0.52 forward. Is that correct? (I haven't independently verified this.)

**Comment by Lucarda** [comment]
> where is the new 'error' function in the pd code?

https://github.com/pure-data/pure-data/blob/master/src/m_pd.h#L544

**Comment by Lucarda** [comment]
@ericlyon 

> My understanding is that error() was replaced with pd_error() from Pd-0.52 forward. Is that correct?

yes. https://github.com/pure-data/pure-data/issues/1530

**Comment by shakfu** [comment]
Yup. https://github.com/pure-data/pure-data/issues/1530 provides some context to the issue. However, it looks like the documentation related to this change is still missing from [current release notes](http://msp.ucsd.edu/Pd_documentation/x5.htm#s1).

**Comment by shakfu** [comment]
Also, please note that the search-and-replace fix is a quick-fix. The point made by Spacechild1 in https://github.com/pure-data/pure-data/issues/1530 still holds:

> but it is almost always better to manually check each occurence of error() as most often you can actually pass an object reference to pd_error() (instead of just NULL).

**Comment by ericlyon** [comment]
I'm fine with approving this merge, unless anyone has any further concerns. I don't see a rush to do anything else until the new API stabilizes and is officially announced. Thanks again @shakfu for calling this matter to my attention. There may be similar issues with https://github.com/ericlyon/pd-fftease.

**Pull request merged**
